//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#ifndef __LH_CONTACT_NODE__
#define __LH_CONTACT_NODE__

#include "cocos2d.h"
#include "Box2D/Box2D.h"
#include "../Nodes/LHContactListener.h"
#include "../Nodes/LHContactInfo.h"

using namespace cocos2d;

class LHContactNodeInfo;

class LHContactNode : public CCNode
{
private:

    
#if COCOS2D_VERSION >= 0x00020000
    CCDictionary preCollisionMap;
    CCDictionary postCollisionMap;
    CCDictionary beginEndCollisionMap;    
#else
    CCMutableDictionary<int> preCollisionMap;
    CCMutableDictionary<int> postCollisionMap;
    CCMutableDictionary<int> beginEndCollisionMap;
#endif
    
    LHContactListener *lhContactListener;
    
public:
    
    LHContactNode(void);
    virtual ~LHContactNode();
    
    bool initContactNodeWithWorld(b2World* world);
    static LHContactNode* contactNodeWithWorld(b2World* world);

    void registerBeginOrEndCollisionCallbackBetweenTagA(int tagA, 
                                                        int tagB,
                                                        CCObject* obj, 
                                                        SEL_CallFuncO sel);

    void cancelBeginOrEndCollisionCallbackBetweenTagA(int tagA,
                                                      int tagB);
    
    void registerPreCollisionCallbackBetweenTagA(int tagA, 
                                                int tagB,
                                                CCObject* obj, 
                                                SEL_CallFuncO sel);
    
    void cancelPreCollisionCallbackBetweenTagA(int tagA,
                                              int tagB);
    
    void registerPostCollisionCallbackBetweenTagA(int tagA,
                                                 int tagB,
                                                 CCObject* obj, 
                                                 SEL_CallFuncO sel);
    
    void cancelPostCollisionCallbackBetweenTagA(int tagA,
                                               int tagB);

    void beginEndSolve(b2Contact* contact, bool isBegin);

    void preSolve(b2Contact* contact,                     
                  const b2Manifold* oldManifold);
    
    void postSolve(b2Contact* contact,
                   const b2ContactImpulse* impulse);

};



#endif	