//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.mm
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////
#include "LHContactInfo.h"
#include "../LevelHelperLoader.h"
#include "LHSettings.h"
#include "LHBezier.h"
#include "LHSprite.h"
#include "LHNode.h"
#include "LHFixture.h"
////////////////////////////////////////////////////////////////////////////////

LHContactInfo::LHContactInfo(void){
    
}
LHContactInfo::~LHContactInfo(void){
   // CCLog("Contact Info dealloc");
}

////////////////////////////////////////////////////////////////////////////////
bool LHContactInfo::initWithInfo(b2Body* _bodyA, 
                                 b2Body* _bodyB,
                                 b2Fixture* fixA,
                                 b2Fixture* fixB,
                                 b2Contact* _contact,
                                 int ctype,
                                 const b2Manifold* _manifold,
                                 const b2ContactImpulse* _impulse){
    
    bodyA = _bodyA;
    bodyB = _bodyB;
    fixtureA = fixA;
    fixtureB = fixB;
    contact = _contact;
    oldManifold = _manifold;
    impulse = _impulse;
    contactType = (LH_CONTACT_TYPE)ctype;
    return true;
}

LHContactInfo* LHContactInfo::contactInfo(b2Body* _bodyA,
                                          b2Body* _bodyB,
                                          b2Fixture* fixA,
                                          b2Fixture* fixB,
                                          b2Contact* _contact,
                                          int ctype,
                                          const b2Manifold* _manifold,
                                          const b2ContactImpulse* _impulse){
    
    LHContactInfo *pobContact = new LHContactInfo();
	if (pobContact && pobContact->initWithInfo(_bodyA, _bodyB, fixA, fixB, _contact,
                                               ctype, _manifold, _impulse)){
	    pobContact->autorelease();
        return pobContact;
    }
    CC_SAFE_DELETE(pobContact);
	return NULL;
}
//------------------------------------------------------------------------------
LHNode* LHContactInfo::nodeA(){
    CCNode* spr = (CCNode*)bodyA->GetUserData();
    if(0 != spr){
        if(LHNode::isLHNode(spr)){
            return (LHNode*)spr;
        }
    }
    return 0;
}
//------------------------------------------------------------------------------
LHNode* LHContactInfo::nodeB(){
    CCNode* spr = (CCNode*)bodyB->GetUserData();
    if(0 != spr){
        if(LHNode::isLHNode(spr)){
            return (LHNode*)spr;
        }
    }
    return 0;
}
//------------------------------------------------------------------------------
LHSprite* LHContactInfo::spriteA(void){
    
    CCNode* spr = (CCNode*)bodyA->GetUserData();
    if(0 != spr){
        if(LHSprite::isLHSprite(spr)){
            return (LHSprite*)spr;
        }
    }
    return 0;
}
//------------------------------------------------------------------------------
LHSprite* LHContactInfo::spriteB(void){
    CCNode* spr = (CCNode*)bodyB->GetUserData();
    if(0 != spr){
        if(LHSprite::isLHSprite(spr)){
            return (LHSprite*)spr;
        }
    }
    return 0;    
}
////////////////////////////////////////////////////////////////////////////////
LHBezier* LHContactInfo::bezierA(void){
    
    CCNode* node = (CCNode*)bodyA->GetUserData();
    if(0 != node){
        if(LHBezier::isLHBezier(node)){
            return (LHBezier*)node;
        }
    }
    return 0;
}
//------------------------------------------------------------------------------
LHBezier* LHContactInfo::bezierB(void){
    
    CCNode* node = (CCNode*)bodyB->GetUserData();
    if(0 != node){
        if(LHBezier::isLHBezier(node)){
            return (LHBezier*)node;
        }
    }
    return 0;
}
//------------------------------------------------------------------------------
LHFixture* LHContactInfo::contactFixtureA()
{
    if(NULL == fixtureA){
        return NULL;
    }
    return (LHFixture*)fixtureA->GetUserData();
}
//------------------------------------------------------------------------------
LHFixture* LHContactInfo::contactFixtureB()
{
    if(NULL == fixtureB)
        return NULL;
    return (LHFixture*)fixtureB->GetUserData();
}
//------------------------------------------------------------------------------
std::string LHContactInfo::fixtureNameA(){
    LHFixture* fixtureA = contactFixtureA();
    if(fixtureA)
        return fixtureA->getFixtureName();
    
    return std::string();
}
//------------------------------------------------------------------------------
std::string LHContactInfo::fixtureNameB(){
    LHFixture* fixtureB = contactFixtureB();
    if(fixtureB)
        return fixtureB->getFixtureName();
    
    return std::string();
}
//------------------------------------------------------------------------------
int LHContactInfo::fixtureIdA(){
    LHFixture* fixtureA = contactFixtureA();
    if(fixtureA)
        return fixtureA->getFixtureID();
    return -1;
}
//------------------------------------------------------------------------------
int LHContactInfo::fixtureIdB(){
    LHFixture* fixtureB = contactFixtureB();
    if(fixtureB)
        return fixtureB->getFixtureID();
    return -1;
}
//------------------------------------------------------------------------------
